[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
